version: "3.9"

services:
  django:
    container_name: westeros
    build: ./westeros
    image: westeros
    env_file:
      - .env
    command: sh /opt/backend/runserver.sh
    volumes:
      - ./westeros:/opt/backend
    ports:
      - 8002:8001
    depends_on:
      - db
      - wdb

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5932:5432
    env_file:
      - .env

  wdb:
    image: docker.io/kozea/wdb
    ports:
      - "127.0.0.1:2094:1984"
    init: true

volumes:
  postgres_data:
